backend:
  type: "postgres"
  user: "postgres"
  pw: "postgres"
  dbname: "dndtext"
authentication:
  accounts: http://mockserver:1080
  oauth2: http://mockserver:1080
  id: "clientid"
  secret: "clientsecret"