version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dndtext
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    ports:
      - "8080:8080"
    depends_on:
      - db

  inttest:
    build: ./inttests/.
    command: "python -m unittest discover -s . -p '*_test.py'"
    depends_on:
      - mockserver
  mockserver:
   image: jamesdbloom/mockserver:mockserver-5.2.3
   ports:
    - 1080:1080
   environment:
    - LOG_LEVEL=INFO